#name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Go modules & build image
        env:
          MODULE_NAME: meshspy
        run: |
          # usa lo script che abbiamo creato
          ./build.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag & Push
        run: |
          IMAGE=meshspy:latest
          TARGET=ghcr.io/${{ github.repository_owner }}/meshspy:latest
          docker tag $IMAGE $TARGET
          docker push $TARGET
